name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: [enhancement]
assignees: [coitate]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Is Your Feature Request Related to a Problem?  
        Please describe the problem you’re trying to solve.  
        (Example: "I'm always frustrated when...")

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      placeholder: Describe the problem you're facing
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 💡 Describe the Solution You’d Like  
        Clearly explain what you’d like to see happen.  
        Be as specific as possible.

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      placeholder: Describe the feature or improvement you'd like to see
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🔄 Describe Alternatives You’ve Considered  
        Have you thought of any alternative solutions or workarounds?  
        Please describe them here.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      placeholder: Mention any alternatives or workarounds you've considered
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 📎 Additional Context  
        Include any other context, mockups, or screenshots that would help us understand your request better.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Add context, screenshots, or mockups here
    validations:
      required: false
