name: 📦 Python Module Installation Request
description: Request the installation of a new Python module in Dify
title: "[Python Module] "
labels: [python-module-request]
assignees: [coitate]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Module Information

  - type: input
    id: module-name
    attributes:
      label: Module Name (as used in pip)
      placeholder: e.g. pyyaml
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version (if specific)
      placeholder: e.g. 6.0.1
    validations:
      required: false

  - type: textarea
    id: module-description
    attributes:
      label: Module Description
      placeholder: Briefly describe what this module does
    validations:
      required: true

  - type: input
    id: module-url
    attributes:
      label: Official Repository or PyPI URL
      placeholder: e.g. https://pypi.org/project/pyyaml/
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 🧩 Purpose and Use Case  
        Describe the problem you’re trying to solve or what functionality you expect from this module.

  - type: textarea
    id: use-case
    attributes:
      label: Purpose and Use Case
      placeholder: |
        e.g. "I need to process YAML files within the code node using the `pyyaml` module."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📝 Additional Context  
        Include any other relevant information.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Code snippets, documentation links, or screenshots
    validations:
      required: false
